package com.javaspeak.designpatterns.go4.behavioural.observer;

/**
 * A SubjectEvent carrying a plain text message.  Being a record, the {@code message()} accessor
 * generated by the compiler implements {@link SubjectEvent#message()} directly.
 *
 * @param message the message describing the event
 *
 * @author John Dickerson - 22 February 2020
 */
public record MessageEvent( String message ) implements SubjectEvent {
}
