package com.javaspeak.designpatterns.go4.behavioural.command;

import java.util.Map;

/**
 * A Request carrying the RequestType and the map of attributes to process.  Being a record, the
 * {@code requestType()} and {@code requestAttributes()} accessors generated by the compiler
 * implement {@link Request#requestType()} and {@link Request#requestAttributes()} directly.
 *
 * @param requestType
 *      The RequestType holds the mapping to a Command.  The RequestProcessor uses the
 *      RequestType from a Request to choose the Command to call execute(..) on.
 *
 * @param requestAttributes
 *      Map of request attributes.  The idea is that the execute(..) method of Command will read
 *      the request attributes, process them and then return them in a new map via the callback
 *      method handleResponse(..) in the response argument of the execute(..) method.
 *
 * @author John Dickerson - 21 February 2020
 */
public record RequestImpl(
        RequestType requestType, Map<String, String> requestAttributes ) implements Request {
}
